<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="1" tests="9" time="1.139" timestamp="2022-08-30T13:54:22.471628" hostname="abigeev"><testcase classname="test_1.TestAuthApi" name="test_create_user_1" file="test_1.py" line="50" time="0.089"><failure message="AssertionError: None == None">self = &lt;test_1.TestAuthApi testMethod=test_create_user_1&gt;

    def test_create_user_1(self):
    	db_session.global_init()
    	response = requests.post(self.api + 'user', json={
    		'token': self.adminToken,
    		'username': 'TestAccontForTest1427',
    		'password': 'test'}, headers=self.headers)
    	self.assertEqual(response.status_code, 200)
&gt;   	self.assertNotEqual(get_user(username='TestAccontForTest1427'), None)
E    AssertionError: None == None

test_1.py:58: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_create_user_2" file="test_1.py" line="60" time="0.020"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_create_user_3" file="test_1.py" line="70" time="0.045"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_delete_user_3" file="test_1.py" line="80" time="0.033"><failure message="AssertionError: 404 != 200">self = &lt;test_1.TestAuthApi testMethod=test_delete_user_3&gt;

    def test_delete_user_3(self):
    	db_session.global_init()
    	response = requests.delete(self.api + 'user', json={
    		'token': self.adminToken,
    		'username': 'TestAccontForTest1427'}, headers=self.headers)
&gt;   	self.assertEqual(response.status_code, 200)
E    AssertionError: 404 != 200

test_1.py:86: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_1" file="test_1.py" line="27" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_2" file="test_1.py" line="33" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_3" file="test_1.py" line="38" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_4" file="test_1.py" line="43" time="0.005"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestEncryptor" name="test_1" file="test_1.py" line="98" time="0.001"><skipped type="pytest.skip" message="Encryption is not ready">D:\Programming\Python\Projects\web_scanner\web_scanner_server\test_1.py:99: Encryption is not ready</skipped><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>