<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="4" skipped="1" tests="9" time="1.320" timestamp="2022-08-30T13:52:03.416962" hostname="abigeev"><testcase classname="test_1.TestAuthApi" name="test_create_user_1" file="test_1.py" line="50" time="0.230"><failure message="TypeError: 'NoneType' object is not callable">self = &lt;test_1.TestAuthApi testMethod=test_create_user_1&gt;

    def test_create_user_1(self):
    	response = requests.post(self.api + 'user', json={
    		'token': self.adminToken,
    		'username': 'TestAccontForTest1427',
    		'password': 'test'}, headers=self.headers)
    	self.assertEqual(response.status_code, 200)
&gt;   	self.assertNotEqual(get_user(username='TestAccontForTest1427'), None)

test_1.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
utils.py:27: in get_user
    session = db_session.create_session()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def create_session() -&gt; Session:
        global __factory
&gt;       return __factory()
E       TypeError: 'NoneType' object is not callable

db_session.py:33: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_create_user_2" file="test_1.py" line="59" time="0.009"><failure message="TypeError: 'NoneType' object is not callable">self = &lt;test_1.TestAuthApi testMethod=test_create_user_2&gt;

    def test_create_user_2(self):
    	response = requests.post(self.api + 'user', json={
    		'token': self.adminToken,
    		'username': self.userLogin,
    		'password': 'test'}, headers=self.headers)
    	self.assertEqual(response.status_code, 409)
&gt;   	self.assertNotEqual(get_user(username=self.userLogin), None)

test_1.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
utils.py:27: in get_user
    session = db_session.create_session()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def create_session() -&gt; Session:
        global __factory
&gt;       return __factory()
E       TypeError: 'NoneType' object is not callable

db_session.py:33: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_create_user_3" file="test_1.py" line="68" time="0.024"><failure message="TypeError: 'NoneType' object is not callable">self = &lt;test_1.TestAuthApi testMethod=test_create_user_3&gt;

    def test_create_user_3(self):
    	response = requests.post(self.api + 'user', json={
    		'token': self.userToken,
    		'username': 'TestAccontForTest1427',
    		'password': 'test'}, headers=self.headers)
    	self.assertEqual(response.status_code, 403)
&gt;   	self.assertNotEqual(get_user(token=self.userToken), 2)

test_1.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
utils.py:27: in get_user
    session = db_session.create_session()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def create_session() -&gt; Session:
        global __factory
&gt;       return __factory()
E       TypeError: 'NoneType' object is not callable

db_session.py:33: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_delete_user_3" file="test_1.py" line="77" time="0.042"><failure message="AssertionError: 404 != 200">self = &lt;test_1.TestAuthApi testMethod=test_delete_user_3&gt;

    def test_delete_user_3(self):
    	response = requests.delete(self.api + 'user', json={
    		'token': self.adminToken,
    		'username': 'TestAccontForTest1427'}, headers=self.headers)
&gt;   	self.assertEqual(response.status_code, 200)
E    AssertionError: 404 != 200

test_1.py:82: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_1" file="test_1.py" line="27" time="0.027"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_2" file="test_1.py" line="33" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_3" file="test_1.py" line="38" time="0.007"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_4" file="test_1.py" line="43" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestEncryptor" name="test_1" file="test_1.py" line="94" time="0.001"><skipped type="pytest.skip" message="Encryption is not ready">D:\Programming\Python\Projects\web_scanner\web_scanner_server\test_1.py:95: Encryption is not ready</skipped><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>